version: '3.8'

services:
  bot:
    image: local/salabot
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - data:/app/data
    restart: unless-stopped
    stop_grace_period: 1m

volumes:
  data:
